### PR TITLE
Bump nginx, nginx-rtmp-module, alpine

### PR DESCRIPTION
**Pull request by oxzi**
- nginx: 1.19.7 -> 1.21.0
- nginx-rtmp-module: 1.2.1 -> 1.2.2
- alpine: 3.13 -> 3.14

### CODE REVIEW

**Comment by alfg** [comment]
Thanks for the upgrade, @oxzi. I will test this out and merge if all is good.

**Comment by alfg** [comment]
Thanks!

**Comment by alfg** [comment]
Ok, this is strange, but the Alpine 1.14 build is failing with a `make: Operation not permitted` only in Docker Hub when building the image and in the TravisCI build. Building locally seems fine, though. 🤔 

I reverted back to `1.13` for the meantime. I'll have to see if the next maintenance version fixes this.

**Comment by oxzi** [comment]
Thanks a lot for your fast review and merging!

> Ok, this is strange, but the Alpine 1.14 build is failing with a
> `make: Operation not permitted` only in Docker Hub when building the
> image and in the TravisCI build. Building locally seems fine, though.

Indeed, this is strange. Locally I have tested the changes successfully
and even deployed the new container.

> I reverted back to `1.13` for the meantime. I'll have to see if the
> next maintenance version fixes this.

Thanks again for your efforts.

**Pull request merged**
