### PR TITLE
fix(cuda): use correct hwaccel arg, add configuration via env in entrypoint

### PR DESCRIPTION
**Pull request by fivethreeo**

### CODE REVIEW

**Comment by alfg** [comment]
@fivethreeo Thanks for your effort on this! The entrypoint script looks great. I may implement something similar for the base image. :)

**Comment by fivethreeo** [comment]
You should change exec to exec_push, forgot that. Also make sure the docker env vars set to "" works

**Comment by fivethreeo** [comment]
Great :)

**Comment by alfg** [comment]
Updated to `exec_push`. Thanks!

**Pull request merged**
